core/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls')),
    path('', include('pets.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pets/urls.py
from django.urls import path

from . import views
from .apiviews import PetListOrCreateView, PetDetailOrUpdateOrDeleteView

app_name = 'pets'

urlpatterns = [
    path('', views.PetListView.as_view(), name='pet_list'),
    path('<int:pk>/', views.PetDetailView.as_view(), name='pet_detail'),
    path('<int:pk>/update/', views.PetUpdateView.as_view(), name='pet_update'),
    path('<int:pk>/delete/', views.PetDeleteView.as_view(), name='pet_delete'),
    path('add/', views.PetCreateView.as_view(), name='pet_create'),
    path("pets/", PetListOrCreateView.as_view(), name="api_pet_list"),
    path("pets/<int:pk>/", PetDetailOrUpdateOrDeleteView.as_view(), name="api_pet_detail"),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

pets/models.py
from django.conf import settings
from django.db import models
from django.db.models import Q
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from imagekit.processors import ResizeToFill
from imagekit.models import ImageSpecField


class Pet(models.Model):
    class Gender(models.TextChoices):
        MALE = 'M', _('Male')
        FEMALE = 'F', _('Female')

    name = models.CharField(_("name"), max_length=64)
    # slug = models.SlugField(_("slug"))
    age = models.IntegerField(_("age"))
    gender = models.CharField(_("gender"), choices=Gender.choices, max_length=1)
    bio = models.TextField(_("bio"), blank=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, null=True,
                              on_delete=models.SET_NULL, verbose_name=_("owner"),
                              related_name="pets")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'pets'   # by default: pets_pet
        verbose_name = _("pet")
        verbose_name_plural = _("pets")
        constraints = [
            models.CheckConstraint(check=Q(age__gte=0) & Q(age__lte=20),
                                   name="chk_pets_age_positive"),
        ]
        # indexes = [
        #     models.Index(fields=["slug"], name="chk_pets_slug"),
        # ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('pets:pet_detail', kwargs={'pk': self.pk})


class Photo(models.Model):
    picture = models.ImageField(_("picture"), upload_to="pets")
    picture_lg = ImageSpecField(source="picture", processors=[
        ResizeToFill(640, 480),
    ], format="JPEG", options={"quality": 70})
    picture_sm = ImageSpecField(source="picture", processors=[
        ResizeToFill(240, 180),
    ], format="JPEG", options={"quality": 70})
    caption = models.CharField(_("caption"), max_length=255, blank=True)
    pet = models.ForeignKey(Pet, verbose_name=_("pet"), on_delete=models.CASCADE, related_name="photos")

    class Meta:
        db_table = 'photos'
        verbose_name = _("photo")
        verbose_name_plural = _("photos")

    def __str__(self):
        if self.caption:
            return self.caption
        return self.picture.name


class Like(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE, related_name="likes",
                             verbose_name=_("user"))
    pet = models.ForeignKey(Pet, verbose_name=_("pet"),
                            on_delete=models.CASCADE, related_name="likes")
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'likes'
        verbose_name = _("like")
        verbose_name_plural = _("likes")
        constraints = [
            models.UniqueConstraint(fields=["user", "pet"], name="uix_likes_users_pets"),
        ]
        # unique_together = ("user", "pet")

users/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

pets/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Button
from django import forms
from django.forms import inlineformset_factory

from .models import Pet, Photo


class PetForm(forms.ModelForm):
    class Meta:
        model = Pet
        fields = ['name', 'age', 'gender', 'bio']


class PhotoInlineForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ['picture', 'caption']


PhotoFormSet = inlineformset_factory(
    Pet,
    Photo,
    extra=1,
    form=PhotoInlineForm,
    min_num=1,
    max_num=10,
)


class PhotoFormHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.form_tag = False
        self.disable_csrf = True
        self.template = 'partials/table_inline_formset.html'

pets/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views import generic

from .forms import PetForm, PhotoFormSet, PhotoFormHelper
from .models import Pet


class PetListView(generic.ListView):
    queryset = Pet.objects.order_by('-created_at').all()
    template_name = 'pets/pet_list.html'
    context_object_name = 'pets'
    paginate_by = 10


class PetDetailView(generic.DetailView):
    model = Pet
    # pk_url_kwarg = 'pk'
    # context_object_name = 'pet'


class PetCreateView(LoginRequiredMixin, generic.CreateView):
    model = Pet
    form_class = PetForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        opts = {}
        if self.request.method == 'POST':
            opts.update({
                "data": self.request.POST,
                "files": self.request.FILES,
            })
        context['formset'] = PhotoFormSet(**opts)
        context['helper'] = PhotoFormHelper()
        return context

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.owner = self.request.user
        self.object.save()
        formset = PhotoFormSet(self.request.POST, files=self.request.FILES,
                               instance=self.object)
        if formset.is_valid():
            formset.save()
        return super().form_valid(form)


class PetUpdateView(generic.UpdateView):
    model = Pet
    form_class = PetForm


class PetDeleteView(generic.DeleteView):
    model = Pet
    success_url = reverse_lazy('pets:pet_list')

users/views.py
# Create your views here.

pets/templates/partials/table_inline_formset.html
{% load crispy_forms_tags %}
{% load crispy_forms_utils %}
{% load crispy_forms_field %}

{% specialspaceless %}
  {% if formset_tag %}
    <form {{ flat_attrs }} method="{{ form_method }}" {% if formset.is_multipart %}
                           enctype="multipart/form-data"{% endif %}>
  {% endif %}
{% if formset_method|lower == 'post' and not disable_csrf %}
  {% csrf_token %}
{% endif %}

<div>
  {{ formset.management_form|crispy }}
</div>

<table{% if form_id %} id="{{ form_id }}_table"{% endif %} class="table table-striped table-sm">
  <thead>
  {% if formset.readonly and not formset.queryset.exists %}
  {% else %}
    <tr>
      {% for field in formset.forms.0 %}
        {% if field.label and not field.is_hidden %}
          <th for="{{ field.auto_id }}" class="{% if field.field.required %}requiredField{% endif %}">
            {{ field.label }}{% if field.field.required and not field|is_checkbox %}
              <span class="asteriskField">*</span>{% endif %}
          </th>
        {% endif %}
      {% endfor %}
      <th>
        <button type="button" class="btn btn-sm btn-success" data-action="add">+</button>
      </th>
    </tr>
  {% endif %}
  </thead>

  <tbody>
  <tr class="d-none empty-form">
    {% for field in formset.empty_form %}
      {% include 'bootstrap5/field.html' with tag="td" form_show_labels=False %}
    {% endfor %}
    <td>
      <button type="button" class="btn btn-sm btn-danger" data-action="remove">-</button>
    </td>
  </tr>

  {% for form in formset %}
    {% if form_show_errors and not form.is_extra %}
      {% include "bootstrap5/errors.html" %}
    {% endif %}

    <tr>
      {% for field in form %}
        {% include 'bootstrap5/field.html' with tag="td" form_show_labels=False %}
      {% endfor %}
      <td>
        {% if not forloop.first %}
          <button type="button" class="btn btn-sm btn-danger" data-action="remove">-</button>
        {% endif %}
      </td>
    </tr>
  {% endfor %}
  </tbody>
</table>

{% include "bootstrap5/inputs.html" %}

{% if formset_tag %}</form>{% endif %}
{% endspecialspaceless %}

pets/templates/pets/pet_detail.html
{% extends "base.html" %}

{% load i18n %}

{% block content %}
    <h1>{{ pet.name }}</h1>
    {% if pet.photos.all %}
    <div id="carouselExampleIndicators" class="carousel slide">
      <div class="carousel-indicators">
        {% for photo in pet.photos.all %}
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="{{ forloop.counter0 }}" {% if forloop.first %}class="active" aria-current="true"{% endif %} aria-label="Slide {{ forloop.counter }}"></button>
        {% endfor %}
      </div>
      <div class="carousel-inner">
        {% for photo in pet.photos.all %}
        <div class="carousel-item{% if forloop.first %} active{% endif %}">
          <img src="{{ photo.picture_lg.url }}" class="d-block w-100" alt="{{ photo.picture.caption }}">
        </div>
        {% endfor %}
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
    {% endif %}
    <h3>{% translate 'Age' %}: {{ pet.age }} {% translate 'year' %}{{ pet.age|pluralize }}</h3>
    <h4>{% translate 'Gender' %}: {{ pet.get_gender_display }}</h4>
    <div>{{ pet.bio }}</div>
{% endblock content %}

pets/templates/pets/pet_form.html
{% extends "base.html" %}
{% load static i18n crispy_forms_tags %}

{% block content %}
  <h1>{% translate 'Add your pet' %}</h1>
  <form class="pet-form" action="" method="post" novalidate enctype="multipart/form-data">
    {% csrf_token %}

    {{ form|crispy }}

    {% crispy formset helper %}

    <button type="submit" class="btn btn-lg btn-secondary">
      {% translate 'Add your pet' %}
    </button>
  </form>
{% endblock content %}

{% block scripts %}
  {{ block.super }}
  <script src="{% static 'scripts/petform.js' %}"></script>
{% endblock scripts %}

pets/templates/pets/pet_list.html
{% extends "base.html" %}

{% load i18n %}

{% block content %}
    <div class="d-flex justify-content-between align-items-center">
        <h1>{% translate 'Latest Pets' %}</h1>
        <a class="btn btn-primary btn-lg" href="{% url 'pets:pet_create' %}">
            <i class="bi bi-plus-square-fill"></i>
            {% translate 'Add your Pet' %}
        </a>
    </div>
{% endblock content %}

templates/base.html
<!doctype html>{% load static %}
<html lang="en" class="h-100" data-bs-theme="auto">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Pets{% endblock title %}</title>
    {% block styles %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link href="{% static 'styles/main.css' %}" rel="stylesheet">
    {% endblock styles %}
  </head>
  <body class="d-flex flex-column h-100">
    <header>
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'pets:pet_list' %}">Pets.al</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'pets:pet_list' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" aria-disabled="true">Disabled</a>
              </li>
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
    </header>

    <main class="flex-shrink-0">
      <div class="container">
        {% block content %}{% endblock content %}
      </div>
    </main>

    <footer class="footer mt-auto py-3 bg-body-tertiary">
      <div class="container">
        <span class="text-body-secondary">Copyright 2024 &copy; Gledi</span>
      </div>
    </footer>
    {% block scripts %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    {% endblock scripts %}
  </body>
</html>